Use exactly match on 'pgrep mysqld' due to mysqld_exporter availability (#50)
* Use exactly match on 'pgrep mysqld' due to mysqld_exporter availability

Otherwise the test may fail with the error:

> Traceback (most recent call last):
>   File "/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/tests/integration/test_bundle.py", line 67, in test_mysql_primary_switchover
>     mysql_pid = await get_process_pid(
>   File "/home/runner/work/mysql-k8s-bundle/mysql-k8s-bundle/tests/integration/helpers.py", line 160, in get_process_pid
>     return int(stripped_pid)
> ValueError: invalid literal for int() with base 10: '69\n353\n409'

* Switch HA test from mysqld to mysqld_safe as we have switched to charmed-mysql snap

* Change helper to use pkill instead of pebble signal

---------

Co-authored-by: Shayan Patel <shayan.patel@canonical.com>